#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/errno.h>

long getFileSize(FILE *fh) {
	long filePos = ftell(fh);
	fseek(fh, 0, SEEK_END);
	long size = ftell(fh);
	fseek(fh, filePos, SEEK_SET);
	return size;
}

void outputChar(FILE *fh, unsigned char c) {
	if(c > 0x9f) {
		fprintf(fh, "0%02Xh", c);
	}
	else {
		fprintf(fh, "%02Xh", c);
	}
}

int main(int argc, char **argv) {
	FILE *binFile = NULL, *incFile = NULL;
	unsigned char *buffer = NULL;
	int ret = 0;
	if(argc != 3) {
		printf("Usage: %s binFile incFile\n", argv[0]);
		return -1;
	}

	binFile = fopen(argv[1], "rb");
	if(binFile == NULL) {
		ret = -2;
		fprintf(stderr, "Couldn't open bin file: %s\n", strerror(errno));
		goto _finish;
	}
	incFile = fopen(argv[2], "wb");
	if(incFile == NULL) {
		ret = -3;
		fprintf(stderr, "Couldn't create inc file: %s\n", strerror(errno));
		goto _finish;
	}

	long size = getFileSize(binFile);
	if(size == 0) {
		ret = -4;
		fprintf(stderr, "Bin file is zero length. Nothing to do.\n");
		goto _finish;
	}

	buffer = malloc(size);
	if(buffer == NULL) {
		ret = -5;
		fprintf(stderr, "Couldn't allocate memory for reading bin file: %s\n", strerror(errno));
		goto _finish;
	}
	
	if(fread(buffer, size, 1, binFile) != 1) {
		ret = -6;
		fprintf(stderr, "Error reading bin file: %s\n", strerror(errno));
		goto _finish;
	}

	fprintf(incFile, "; ---> This file has been auto-generated by bin2inc from %s <---", argv[1]);

	for(long i = 0; i < size; i++) {
		if(i % 16 == 0) {
			fprintf(incFile, "\n\tdb\t");
			outputChar(incFile, buffer[i]);
		}
		else {
			fprintf(incFile, ", ");
			outputChar(incFile, buffer[i]);
		}
		
	}

_finish:
	if(buffer != NULL) {
		free(buffer);
		buffer = NULL;
	}
	if(binFile != NULL) {
		fclose(binFile);
		binFile = NULL;
	}
	if(incFile != NULL) {
		fclose(incFile);
		incFile = NULL;
	}
	return ret;
}
