
EXES=bin2inc bin2font oddeven

all: $(EXES)

oddeven: oddeven.c
	$(CC) -o oddeven oddeven.c

bin2inc: bin2inc.c
	$(CC) -o bin2inc bin2inc.c

bin2font: bin2font.c
	$(CC) -o bin2font bin2font.c

clean:
	rm bin2inc oddeven bin2font

